name: Build and Test

on:
  pull_request:
    branches:
      - develop

env:
  APP_ENV: test
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Run App
        run: task install

      - name: Wait for app
        run: task docker:wait-for

      - name: Run Health check
        run: task health-check -- localhost:3000
